/* ===== js/vehicles-db.js ===== */

const vehiclesDatabase = [
  { id: 1,   name: "Acura NSX" },
  { id: 2,   name: "Alfa Romeo Giulia" },
  { id: 3,   name: "Audi 80 Avant (B4)" },
  { id: 4,   name: "Audi A3 sedan" },
  { id: 5,   name: "Audi A4 Allroad quattro" },
  { id: 6,   name: "Audi A8 (D4)" },
  { id: 7,   name: "Audi Q7 TDI" },
  { id: 8,   name: "Audi Q7 V12 TDI" },
  { id: 9,   name: "Audi R8" },
  { id: 10,  name: "Audi RS6 Avant (C7)" },
  { id: 11,  name: "Audi RS6 Avant (C8)" },
  { id: 12,  name: "Audi RS6-R (C8) ABT" },
  { id: 13,  name: "Audi RS7 (C8)" },
  { id: 14,  name: "Audi S4 (B8)" },
  { id: 15,  name: "Audi S8 Plus (D4)" },
  { id: 16,  name: "Audi SQ8" },
  { id: 17,  name: "Bentley Bentayga W12" },
  { id: 18,  name: "Bentley Continental GT" },
  { id: 19,  name: "BMW 535i (E34)" },
  { id: 20,  name: "BMW 530d (E39)" },
  { id: 21,  name: "BMW 530d Touring (F11)" },
  { id: 22,  name: "BMW 750i (E38)" },
  { id: 23,  name: "BMW 850 CSi" },
  { id: 24,  name: "BMW M3 (e46)" },
  { id: 25,  name: "BMW M3 (E46) «Most Wanted»" },
  { id: 26,  name: "BMW M3 (E46) «Most Wanted Edition»" },
  { id: 27,  name: "BMW M3 (e92)" },
  { id: 28,  name: "BMW M4 (F82)" },
  { id: 29,  name: "BMW M4 (G82)" },
  { id: 30,  name: "BMW M4 (G82) CSL" },
  { id: 31,  name: "BMW M5 (E60)" },
  { id: 32,  name: "BMW M5 (F90)" },
  { id: 33,  name: "BMW M5 (F90) LCI" },
  { id: 34,  name: "BMW M6 (F13)" },
  { id: 35,  name: "BMW M6 (F13) HAMANN «Mirror»" },
  { id: 36,  name: "BMW M760 Li xDrive (G12)" },
  { id: 37,  name: "BMW M8 Competition" },
  { id: 38,  name: "BMW M8 Competition «Radio Legend»" },
  { id: 39,  name: "BMW S1000RR" },
  { id: 40,  name: "BMW X5 (E53)" },
  { id: 41,  name: "BMW X5 M (F85)" },
  { id: 42,  name: "BMW X5 M (F95)" },
  { id: 43,  name: "BMW X6 M (F86)" },
  { id: 44,  name: "BMW X6 M (F96)" },
  { id: 45,  name: "BMW X7" },
  { id: 46,  name: "BMW Z4" },
  { id: 47,  name: "Богдан А092" },
  { id: 48,  name: "Богдан А09302" },
  { id: 49,  name: "Богдан А09304 Атаман" },
  { id: 50,  name: "Bugatti Chiron Sport" },
  { id: 51,  name: "Bugatti Chiron Super Sport" },
  { id: 52,  name: "Cadillac CTS-V" },
  { id: 53,  name: "Cadillac Escalade ESV" },
  { id: 54,  name: "Chevrolet Camaro ZL1" },
  { id: 55,  name: "Chevrolet Camaro ZL1 «Spooky»" },
  { id: 56,  name: "Chevrolet Caprice Classic" },
  { id: 57,  name: "Chevrolet Caprice Classic «Purple Rose»" },
  { id: 58,  name: "Chevrolet Corvette ZR1" },
  { id: 59,  name: "Chevrolet Cruze" },
  { id: 60,  name: "Chevrolet El Camino SS" },
  { id: 61,  name: "Chevrolet El Camino SS «Dia de los Muertos»" },
  { id: 62,  name: "Chevrolet Lacetti" },
  { id: 63,  name: "Chevrolet Niva" },
  { id: 64,  name: "Chevrolet Suburban" },
  { id: 65,  name: "Chevrolet Tahoe LTZ" },
  { id: 66,  name: "Daewoo Matiz" },
  { id: 67,  name: "Dodge Challenger SRT Demon" },
  { id: 68,  name: "Dodge Challenger SRT Hellcat" },
  { id: 69,  name: "Dodge Charger R/T 1969" },
  { id: 70,  name: "Dodge Charger SRT Hellcat" },
  { id: 71,  name: "Dodge Charger SRT Hellcat «10th Anniversary»" },
  { id: 72,  name: "Dodge Charger SRT Hellcat «Demon's Spring»" },
  { id: 73,  name: "Ducati Diavel Carbon" },
  { id: 74,  name: "Ferrari 348 GTB" },
  { id: 75,  name: "Ferrari 348 GTS" },
  { id: 76,  name: "Ferrari 488 GTB" },
  { id: 77,  name: "Ferrari 488 GTB «Liberty Walk»" },
  { id: 78,  name: "Ferrari LaFerrari" },
  { id: 79,  name: "Ferrari Portofino" },
  { id: 80,  name: "Ferrari Purosangue" },
  { id: 81,  name: "Ford F-150 Shelby 2020" },
  { id: 82,  name: "Ford F-150 Shelby «Silver Skull»" },
  { id: 83,  name: "Ford F-450" },
  { id: 84,  name: "Ford Focus 3" },
  { id: 85,  name: "Ford Mustang GT 2015" },
  { id: 86,  name: "Ford Mustang Shelby GT500" },
  { id: 87,  name: "Ford Mustang Shelby GT500 «Eleanor»" },
  { id: 88,  name: "GMC Vandura" },
  { id: 89,  name: "GMC Vandura «The Mystery Machine»" },
  { id: 90,  name: "Harley-Davidson Fat Boy Lo" },
  { id: 91,  name: "Harley-Davidson Sportster S" },
  { id: 92,  name: "Honda Accord" },
  { id: 93,  name: "Honda CBR1100XX Super Blackbird" },
  { id: 94,  name: "Honda Civic Type-R" },
  { id: 95,  name: "Honda Civic Type-R «Underground»" },
  { id: 96,  name: "Honda Dio AF 35 ZX" },
  { id: 97,  name: "Honda Gold Wing GL1500" },
  { id: 98,  name: "Honda NSX" },
  { id: 99,  name: "Hummer H2" },
  { id: 100, name: "Ikarus 250.59" },
  { id: 101, name: "Ikarus 256.54" },
  { id: 102, name: "Ikarus 260 (планетарные двери)" },
  { id: 103, name: "Ikarus 260 (ширмовые двери)" },
  { id: 104, name: "Indian Chief Dark Horse" },
  { id: 105, name: "Indian Chief Dark Horse «Fire Chopper»" },
  { id: 106, name: "Indian Chief Dark Horse «The Lone Wolf»" },
  { id: 107, name: "Indian Chief Dark Horse «Vintage»" },
  { id: 108, name: "Infiniti QX80" },
  { id: 109, name: "ИЖ 21251 Комби" },
  { id: 110, name: "Jaguar F-Type R" },
  { id: 111, name: "Jeep Grand Cherokee (ZJ)" },
  { id: 112, name: "Jeep Grand Cherokee Trackhawk" },
  { id: 113, name: "Jeep Wrangler Rubicon" },
  { id: 114, name: "Jeep Wrangler Rubicon «Кровавый»" },
  { id: 115, name: "KAMAZ-5490 NEO" },
  { id: 116, name: "Kawasaki Vulcan VN900 Classic" },
  { id: 117, name: "КАвЗ-3270" },
  { id: 118, name: "КАвЗ-4238 Аврора" },
  { id: 119, name: "КАвЗ-685М" },
  { id: 120, name: "KIA Optima SXL" },
  { id: 121, name: "KIA Rio" },
  { id: 122, name: "KIA Stinger GT" },
  { id: 123, name: "KTM 690 Enduro R" },
  { id: 124, name: "Lada 4x4 Urban" },
  { id: 125, name: "Lada Granta" },
  { id: 126, name: "Lada Largus" },
  { id: 127, name: "Lada Priora" },
  { id: 128, name: "Lada Vesta" },
  { id: 129, name: "Lada Vesta Sport" },
  { id: 130, name: "Lamborghini Aventador S Roadster" },
  { id: 131, name: "Lamborghini Huracan EVO" },
  { id: 132, name: "Lamborghini Huracan Sterrato" },
  { id: 133, name: "Lamborghini Urus" },
  { id: 134, name: "Land Rover Range Rover" },
  { id: 135, name: "ЛАЗ-4207" },
  { id: 136, name: "ЛАЗ-5207" },
  { id: 137, name: "ЛАЗ-695Н" },
  { id: 138, name: "ЛАЗ-695Н «Дедморобус»" },
  { id: 139, name: "ЛАЗ-697Р Турист" },
  { id: 140, name: "ЛАЗ-699Р Турист" },
  { id: 141, name: "Lexus IS 350 F" },
  { id: 142, name: "Lexus LFA" },
  { id: 143, name: "Lexus LX570" },
  { id: 144, name: "Li L9" },
  { id: 145, name: "ЛиАЗ 5256.00-11" },
  { id: 146, name: "ЛиАЗ 5256.40" },
  { id: 147, name: "ЛиАЗ 5292.22" },
  { id: 148, name: "ЛиАЗ-5256.00" },
  { id: 149, name: "ЛиАЗ-5256.00 (поздний вариант)" },
  { id: 150, name: "ЛиАЗ-677 (ранний)" },
  { id: 151, name: "ЛиАЗ-677М" },
  { id: 152, name: "ЛиАЗ-677М «Дедморобус»" },
  { id: 153, name: "ЛиАЗ-677Э (экспортный)" },
  { id: 154, name: "ЛиАЗ 4292" },
  { id: 155, name: "Maseratti GranTurismo" },
  { id: 156, name: "Mazda 3" },
  { id: 157, name: "Mazda RX-7 (FD)" },
  { id: 158, name: "Mazda RX-8" },
  { id: 159, name: "МАЗ-203" },
  { id: 160, name: "McLaren 720S Spyder" },
  { id: 161, name: "Mercedes-AMG GT 63 S 4MATIC+" },
  { id: 162, name: "Mercedes-AMG GT R" },
  { id: 163, name: "Mercedes-Benz 190E (W201)" },
  { id: 164, name: "Mercedes-Benz 190E (W201) AMG 3.2 «Barolorot»" },
  { id: 165, name: "Mercedes-Benz 190E (W201) AMG 3.2 «Blauschwartz»" },
  { id: 166, name: "Mercedes-Benz 190E (W201) AMG 3.2 «Classic Weiss»" },
  { id: 167, name: "Mercedes-Benz 250D (W124)" },
  { id: 168, name: "Mercedes-Benz 560SEL (W126)" },
  { id: 169, name: "Mercedes-Benz 600SEL (W140)" },
  { id: 170, name: "Mercedes-Benz Actros" },
  { id: 171, name: "Mercedes-Benz C200 (W206)" },
  { id: 172, name: "Mercedes-Benz C63 AMG (W204)" },
  { id: 173, name: "Mercedes-Benz C63 AMG (W204) «Камуфляж»" },
  { id: 174, name: "Mercedes-Benz C63 AMG (W204) «Сакура»" },
  { id: 175, name: "Mercedes-Benz C63 S Coupe AMG (W205)" },
  { id: 176, name: "Mercedes-Benz CLS63 AMG (C218) Дорест" },
  { id: 177, name: "Mercedes-Benz CLS63 AMG (C218) Рестайлинг" },
  { id: 178, name: "Mercedes-Benz E240 (W210)" },
  { id: 179, name: "Mercedes-Benz E63 S AMG (W212)" },
  { id: 180, name: "Mercedes-Benz E63 S AMG (W213)" },
  { id: 181, name: "Mercedes-Benz E63 S (W213) рестайлинг" },
  { id: 182, name: "Mercedes-Benz G500 (W464)" },
  { id: 183, name: "Mercedes-Benz G63 AMG (W464)" },
  { id: 184, name: "Mercedes-Benz G65 AMG (W463)" },
  { id: 185, name: "Mercedes-Benz GLE Coupe 450d" },
  { id: 186, name: "Mercedes-Benz GLS63 AMG" },
  { id: 187, name: "Mercedes-Benz ML 63 AMG (W164)" },
  { id: 188, name: "Mercedes-Benz S600 (W220)" },
  { id: 189, name: "Mercedes-Benz Sprinter Classic 311 CDI" },
  { id: 190, name: "Mercedes-Benz Sprinter Classic 411 CDI (AS3)" },
  { id: 191, name: "Mercedes-Benz Sprinter Classic 411 CDI (Base)" },
  { id: 192, name: "Mercedes-Benz V300d" },
  { id: 193, name: "Mercedes-Maybach S650 (X222)" },
  { id: 194, name: "Mitsubishi Lancer Evolution IX MR" },
  { id: 195, name: "Mitsubishi Lancer Evolution X" },
  { id: 196, name: "Mitsubishi Lancer Evolution X «Фантом»" },
  { id: 197, name: "Москвич 2141S" },
  { id: 198, name: "Москвич-2140" },
  { id: 199, name: "Nissan 200SX" },
  { id: 200, name: "Nissan 350Z" },
  { id: 201, name: "Nissan 400Z" },
  { id: 202, name: "Nissan 400Z Pandem «Senshi»" },
  { id: 203, name: "Nissan GT-R (R35)" },
  { id: 204, name: "Nissan GT-R (R35) «Radio Province»" },
  { id: 205, name: "Nissan Leaf" },
  { id: 206, name: "Nissan Silvia S15 Spec-R" },
  { id: 207, name: "Nissan Silvia S15 Spec-R «Akima»" },
  { id: 208, name: "Nissan Skyline GT-R V-spec (R34)" },
  { id: 209, name: "Nissan Skyline GTS-T Type-M (R-32)" },
  { id: 210, name: "Nissan Stagea" },
  { id: 211, name: "ПАЗ 672М" },
  { id: 212, name: "ПАЗ Vector Next «Radio Province»" },
  { id: 213, name: "ПАЗ-32053 (бензин)" },
  { id: 214, name: "ПАЗ-32053 рестайлинг (бензин)" },
  { id: 215, name: "ПАЗ-32054 (бензин)" },
  { id: 216, name: "ПАЗ-32054 (дизель)" },
  { id: 217, name: "ПАЗ-32054 рестайлинг (бензин)" },
  { id: 218, name: "ПАЗ-320405-04 Вектор Next" },
  { id: 219, name: "ПАЗ-320414-05 Вектор" },
  { id: 220, name: "ПАЗ-4230 Аврора" },
  { id: 221, name: "ПАЗ-4234 (дизель)" },
  { id: 222, name: "ПАЗ-672М «Дедморобус»" },
  { id: 223, name: "Peugeot 207" },
  { id: 224, name: "Peugeot 406" },
  { id: 225, name: "Porsche 911 Carrera (993) RWB «Slimmer»" },
  { id: 226, name: "Porsche 911 Carrera 993" },
  { id: 227, name: "Porsche 911 Carrera S (992)" },
  { id: 228, name: "Porsche 911 GT3 (992)" },
  { id: 229, name: "Porsche 911 Turbo S (992)" },
  { id: 230, name: "Porsche 911 Turbo S (992) «Cyberpunk»" },
  { id: 231, name: "Porsche 911 Turbo S «Тыквоголовая»" },
  { id: 232, name: "Porsche Cayenne Turbo" },
  { id: 233, name: "Porsche Panamera Turbo" },
  { id: 234, name: "Porsche Panamera Turbo S Sport Turismo" },
  { id: 235, name: "Porsche Taycan Turbo S" },
  { id: 236, name: "RAM TRX" },
  { id: 237, name: "RAM TRX Icebreaker" },
  { id: 238, name: "Range Rover (L460)" },
  { id: 239, name: "Range Rover Sport SVR" },
  { id: 240, name: "Range Rover SVAutobiography" },
  { id: 241, name: "Renault Logan" },
  { id: 242, name: "Renault Magnum" },
  { id: 243, name: "Renault Megane" },
  { id: 244, name: "Rolls-Royce Cullinan" },
  { id: 245, name: "Rolls-Royce Phantom VIII" },
  { id: 246, name: "Rolls-Royce Wraith" },
  { id: 247, name: "Scania OmniLink CK95UB 4x2 LB (2 doors)" },
  { id: 248, name: "Scania OmniLink CK95UB 4x2 LB (3 doors)" },
  { id: 249, name: "Scania R500" },
  { id: 250, name: "Scania Topline R480" },
  { id: 251, name: "Skoda Octavia" },
  { id: 252, name: "Skoda Rapid 2020" },
  { id: 253, name: "Skoda Superb" },
  { id: 254, name: "Subaru BRZ" },
  { id: 255, name: "Subaru Forester (SG9)" },
  { id: 256, name: "Subaru Forester XT" },
  { id: 257, name: "Subaru Impreza WRX STI" },
  { id: 258, name: "Subaru Impreza WRX STI «Снежинка»" },
  { id: 259, name: "Subaru WRX STI (VA)" },
  { id: 260, name: "Suzuki GSX 1300 R Hayabusa" },
  { id: 261, name: "Tesla Model S Plaid" },
  { id: 262, name: "Tesla Model S «Radio Province»" },
  { id: 263, name: "Tesla Model X Plaid" },
  { id: 264, name: "Toyota Altezza RS200" },
  { id: 265, name: "Toyota Camry 3.5 (XV70)" },
  { id: 266, name: "Toyota Chaser Tourer V (JZX100)" },
  { id: 267, name: "Toyota Chaser Tourer V (JZX100) Дорестайлинг" },
  { id: 268, name: "Toyota Land Cruiser 200 Executive Lounge" },
  { id: 269, name: "Toyota Land Cruiser 300" },
  { id: 270, name: "Toyota Land Cruiser Prado" },
  { id: 271, name: "Toyota Mark II Tourer V (100JZX)" },
  { id: 272, name: "Toyota Mark II Tourer V (90JZX)" },
  { id: 273, name: "Toyota Supra (A80)" },
  { id: 274, name: "Toyota Supra (A90)" },
  { id: 275, name: "Toyota Supra (A90) Targa" },
  { id: 276, name: "Toyota Tundra" },
  { id: 277, name: "УАЗ-2206 Буханка" },
  { id: 278, name: "УАЗ-3909" },
  { id: 279, name: "УАЗ-3909 «Оборона»" },
  { id: 280, name: "УАЗ-469" },
  { id: 281, name: "УАЗ Хантер" },
  { id: 282, name: "УАЗ Хантер «Победа»" },
  { id: 283, name: "УАЗ Патриот" },
  { id: 284, name: "ВАЗ-1111 Ока" },
  { id: 285, name: "ВАЗ-1111 «Ока» FOOL'S DAY" },
  { id: 286, name: "ВАЗ-2101" },
  { id: 287, name: "ВАЗ-21011 «Сгущёнка»" },
  { id: 288, name: "ВАЗ-21011 «Сода»" },
  { id: 289, name: "ВАЗ-2104" },
  { id: 290, name: "ВАЗ-2106" },
  { id: 291, name: "ВАЗ-2107" },
  { id: 292, name: "ВАЗ-2107 «Joke»" },
  { id: 293, name: "ВАЗ-2107 VFTS «Autumn Drift»" },
  { id: 294, name: "ВАЗ-2108" },
  { id: 295, name: "ВАЗ-2108 «Буран»" },
  { id: 296, name: "ВАЗ-2108 «Birthday Race»" },
  { id: 297, name: "ВАЗ-2108 Рестайлинг" },
  { id: 298, name: "ВАЗ-2109" },
  { id: 299, name: "ВАЗ-2109 Рестайлинг" },
  { id: 300, name: "ВАЗ-21099" },
  { id: 301, name: "ВАЗ-2110" },
  { id: 302, name: "ВАЗ-21124" },
  { id: 303, name: "ВАЗ-2113" },
  { id: 304, name: "ВАЗ-2114" },
  { id: 305, name: "ВАЗ-2115" },
  { id: 306, name: "Volkswagen Golf 2.0 TSI (VI)" },
  { id: 307, name: "Volkswagen Golf IV" },
  { id: 308, name: "Volkswagen Jetta" },
  { id: 309, name: "Volkswagen Multivan T6.1" },
  { id: 310, name: "Volkswagen Passat GL (B3)" },
  { id: 311, name: "Volkswagen Polo" },
  { id: 312, name: "Volkswagen Touareg V8 TDI" },
  { id: 313, name: "Volvo 850 R" },
  { id: 314, name: "Volvo FH" },
  { id: 315, name: "Volvo V60 Polestar" },
  { id: 316, name: "Volvo VNL" },
  { id: 317, name: "Volvo XC90 T5" },
  { id: 318, name: "Yamaha WR250F" },
  { id: 319, name: "Yamaha XT660" },
  { id: 320, name: "Yamaha XVS400 Drag Star" },
  { id: 321, name: "Yamaha XVS400 Drag Star Classic" },
  { id: 322, name: "ЗАЗ-968 «Запорожец»" },
  { id: 323, name: "ГАЗ-13 «Чайка»" },
  { id: 324, name: "ГАЗ-13 «Чайка» 9 Мая" },
  { id: 325, name: "ГАЗ-24 «Космос»" },
  { id: 326, name: "ГАЗ-24 Волга" },
  { id: 327, name: "ГАЗ-3102" },
  { id: 328, name: "ГАЗ-3102 «Защитник»" },
  { id: 329, name: "ГАЗ-3110 Волга" },
  { id: 330, name: "ГАЗ-3302 Будка" },
  { id: 331, name: "ГАЗ-3302 Тент" },
  { id: 332, name: "ГАЗ-3309 Дорест" },
  { id: 333, name: "ГАЗ-3309 Рест" },
  { id: 334, name: "ГАЗ-66" },
  { id: 335, name: "ГАЗель БИЗНЕС" },
  { id: 336, name: "ГАЗель NEXT" },
  { id: 337, name: "ГАЗель NEXT" },
  { id: 338, name: "ГАЗель NEXT" },
  { id: 339, name: "ГАЗель NEXT A64R42 Ситилайн" },
  { id: 340, name: "ГАЗ-М20 «Победа»" },
  { id: 341, name: "ЗИЛ 131 Тент" },
  { id: 342, name: "ЗИЛ 133540" },
  { id: 343, name: "ИЖ Юпитер-5" },
  { id: 344, name: "КамАЗ 53212 Контейнер" },
  { id: 345, name: "КамАЗ 53212 Тент" },
  { id: 346, name: "КамАЗ 54115" }
];

const locationsDatabase = [
  "Приволжск, Автодром",
  "Приволжск, Автомастерская",
  "Приволжск, Авторынок",
  "Приволжск, Автосалон «Mercury-Auto»",
  "Приволжск, Автостоянка",
  "Приволжск, Автошкола",
  "Приволжск, Аренда авто",
  "Приволжск, Аренда велосипедов",
  "Приволжск, Аренда лодок",
  "Приволжск, АТП No1",
  "Приволжск, АТП No2",
  "Приволжск, Аэропорт",
  "Приволжск, Банк",
  "Приволжск, Бар",
  "Приволжск, Больница",
  "Приволжск, Военкомат",
  "Приволжск, Вокзал",
  "Приволжск, Гоночный трек",
  "Приволжск, Гостиница «Кварт»",
  "Приволжск, Дрифт-трек",
  "Приволжск, Завод ЖБК",
  "Приволжск, Кинотеатр «Огонек»",
  "Приволжск, Магазин «Планета Секонд хенд»",
  "Приволжск, Макдоналдс",
  "Приволжск, Метродепо",
  "Приволжск, Мэрия",
  "Приволжск, Оружейный магазин",
  "Приволжск, Офисный центр",
  "Приволжск, Пиццерия «Вито»",
  "Приволжск, Полицейский участок",
  "Приволжск, Порт",
  "Приволжск, ПТЭЦ",
  "Приволжск, Речной вокзал",
  "Приволжск, Рынок",
  "Приволжск, Стройплощадка",
  "Приволжск, Таксопарк",
  "Приволжск, Тестовый автотрек",
  "Приволжск, Трамвайное депо №1",
  "Приволжск, Трамвайное депо №2",
  "Приволжск, Транспортная компания",
  "Приволжск, ТРК «ВиваЛэнд»",
  "Приволжск, Троллейбусное дело",
  "Приволжск, ТТУ",
  "Приволжск, ТЦ «Лента»",
  "Приволжск, ТЦ «Линкор»",
  "Приволжск, ТЦ «Моксадим»",
  "Приволжск, Тюнинг ателье",
  "Приволжск, Церковь",
  "Приволжск (пригород), Деревня Азино",
  "Жуковский, АТП",
  "Жуковский, ЖТУ/Лесопилка",
  "Жуковский, Таксопарк",
  "Мирный, Автодром",
  "Мирный, Автомастерская",
  "Мирный, Автосалон «Мир Авто»",
  "Мирный, Автосалон «МирБус»",
  "Мирный, Автостоянка",
  "Мирный, Автошкола",
  "Мирный, Аренда авто",
  "Мирный, Аренда велосипедов",
  "Мирный, Аренда лодок",
  "Мирный, АТП",
  "Мирный, АЭС «Мирн Атом»",
  "Мирный, База отдыха «Золотой дождик»",
  "Мирный, Банк",
  "Мирный, Больница",
  "Мирный, Военкомат",
  "Мирный, Воинская часть",
  "Мирный, Гостиница Космос",
  "Мирный, Доставка пиццы",
  "Мирный, Железнодорожный вокзал",
  "Мирный, Здание РЖД",
  "Мирный, Казино",
  "Мирный, Кинотеатр",
  "Мирный, Клуб",
  "Мирный, Летная школа",
  "Мирный, Макдоналдс",
  "Мирный, Мусорная свалка",
  "Мирный, Мэрия",
  "Мирный, Офисный центр",
  "Мирный, Парк Дружбы",
  "Мирный, Полиция",
  "Мирный, Прыжок с парашютом",
  "Мирный, Речной вокзал",
  "Мирный, Свалка авто",
  "Мирный, Спортивный зал",
  "Мирный, Стадион",
  "Мирный, Стройплощадка №1",
  "Мирный, Стройплощадка №2",
  "Мирный, Таксопарк",
  "Мирный, Трамвайное депо",
  "Мирный, Транспортная компания",
  "Мирный, Троллейбусное депо",
  "Мирный, ТРК «Тандем»",
  "Мирный, ТРЦ «Сити-парк Град»",
  "Мирный, ТТУ",
  "Мирный, Тюнинг ателье",
  "Мирный, Шахта",
  "Мирный, Электродепо монорельса",
  "Мирный (пригород), Деревня «Водино»",
  "Мирный (пригород), Деревня «Горная»",
  "Мирный (пригород), Деревня «Озерки»",
  "Невский, Автомастерская",
  "Невский, Автосалоны",
  "Невский, Автостоянка",
  "Невский, Автошкола",
  "Невский, Аренда авто",
  "Невский, Аренда лодок",
  "Невский, АТП",
  "Невский, Банк",
  "Невский, Больница",
  "Невский, Вокзал",
  "Невский, Водная школа/Экскурсионная компания",
  "Невский, Военкомат",
  "Невский, Гостиница Mamajest",
  "Невский, Дворцовая площадь",
  "Невский, Завод «Красный октябрь»",
  "Невский, Магазин «Трикотажный мир»",
  "Невский, Макдоналдс",
  "Невский, Метродепо",
  "Невский, Мэрия",
  "Невский, Оружейный магазин",
  "Невский, Офисный центр",
  "Невский, Полиция",
  "Невский, Порт",
  "Невский, Речная пристань",
  "Невский, Речной вокзал",
  "Невский, Стрелка Васильевского острова",
  "Невский, Табачный завод",
  "Невский, Таксопарк",
  "Невский, Тир",
  "Невский, Транспортная компания",
  "Невский, ТРЦ «Парус»",
  "Невский, ТТУ",
  "Невский, ТЦ «Ареал»",
  "Невский, ТЭЦ",
  "Невский, Тюнинг ателье",
  "Волчанск, Автостанция",
  "Волчанск, АТП",
  "Волчанск, ВТУ"
];

window.vehiclesDatabase = vehiclesDatabase;
window.locationsDatabase = locationsDatabase;